version: 1.0.0.{build}

# Install scripts. (runs after repo cloning)
install:
  - npm install

# Post-install scripts.
test_script:
  - node .\node_modules\resume-cli\index.js export index -f html --theme modern
  - node .\node_modules\resume-cli\index.js export resume -f pdf --theme modern

# Don't actually build.
build: off

artifacts:
  - path: index.html
    name: Resume (HTML format)
  - path: resume.pdf
    name: Resume (PDF format)    
  
