version: 1.0.0.{build}

# Install scripts. (runs after repo cloning)
install:
  - npm install

# Post-install scripts.
test_script:
  - node .\node_modules\resume-cli\index.js export index -f html --theme elegant
  - node .\node_modules\resume-cli\index.js export index-flat -f html --theme flat
  - node .\node_modules\resume-cli\index.js export index-modern -f html --theme modern  
  - node .\node_modules\resume-cli\index.js export resume -f pdf --theme elegant
  - node .\node_modules\resume-cli\index.js export resume-flat -f pdf --theme flat
  - node .\node_modules\resume-cli\index.js export resume-modern -f pdf --theme modern 

# Don't actually build.
build: off

artifacts:
  - path: index.html
    name: Résumé  of Hannes Sachsenhofer (elegant theme)
  - path: index-flat.html
    name: Résumé  of Hannes Sachsenhofer (flat theme)
  - path: index-modern.html
    name: Résumé  of Hannes Sachsenhofer (modern theme)    
  - path: resume.pdf
    name: Résumé  of Hannes Sachsenhofer (elegant theme)
  - path: resume-flat.pdf
    name: Résumé  of Hannes Sachsenhofer (flat theme)
  - path: resume-modern.pdf
    name: Résumé  of Hannes Sachsenhofer (modern theme)
    
# Deploy all artifacts to GitHub Releases
deploy:
  release: Hannes_Sachsenhofer_Resume-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: /ix/M1BB3mfWKuVd3Z/t6VsLBJM8w6ijyeFaC/fMV/I7qBlAtMwXaLzAIQEnViP7
  # artifact: /.*\.html/ # left out, because all artifacts should be deployed
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
  
